### PR TITLE
Print style #27

### LINKED ISSUE #27: Clean up print style
-Remove code that is not used from the print style.
-Test the print style.

### PR DESCRIPTION
**Pull request by pilarmera**
Hi!
I've been testing the print style (Firefox on Ubuntu and Chrome on Mac), see #27 , added a few tweaks:
- stretch content to the margins
- applied small and light style for links
- layout for captions and links on gallery, cover and images blocks
- border for embeds and audio

I hope it helps, let me know if I should add or remove anything, I'm willing to help :)

### CODE REVIEW

**Comment by melchoyce** [comment]
Thanks @decrecementofeliz, this is a great start!

Some ideas...
- Reduce the size of the site title and url that shows up at the top of the print stylesheet
- Same with post titles
- Hide pagination
- Unstyle buttons so they just look like links

**Comment by pilarmera** [comment]
Checked buttons and titles sizes. Regarding the page headers, footers and pagination, afaik they are controlled by the browser only, I can't change them.

**Comment by aristath** [comment]
@decrecementofeliz any update on this one?

**Comment by pilarmera** [comment]
Sorry! I didn't notice I had used another account -connected in github desktop- for my previous commit. I have just resent the changes, hih
Thank you

**Comment by rolf-yoast** [comment]
LGTM 👍

**Pull request merged**
