### PR TITLE
Fix 398 fix site header alignment

### LINKED ISSUE #398: Site navigation should centre aligned to Site Branding section
**Describe the bug**
Site navigation(Primary Navigation) is not horizontally aligned to Site Branding Section.

**To Reproduce**
1. Go to 'Appearance - Menu`
2. Create Primary Navigation
3. Go to Customizer and add Logo
4. Refresh the page
5. See Primary Navigation and Site Branding section you will see the difference

**Expected behavior**
Primary Navigation should centre aligned with the Site Branding section

**Screenshots**
https://a.cl.ly/Qwuk0e4B

### PR DESCRIPTION
**Pull request by JustinyAhin**
Fixes #398

## Summary
Center vertically the navigation when there is a custom logo.

## Relevant technical choices:
No

## Test instructions

This PR can be tested by following these steps:

1. Add a primary navigation menu to the site
2. Add a custom logo to the site
3. On frontend, the navigation menu should be vertically aligned in the site `header`

## Quality assurance
* [x] I have thought about any security implications this code might add.
* [x] I have checked that this code doesn't impact performance (greatly).
* [x] I have tested this code to the best of my abilities
* [x] I have checked that this code does not affect the accessibility negatively

### CODE REVIEW

**Review by carolinan — APPROVED** [review]
Looks good to me.  

@melchoyce Needs design feedback before merge.

**Comment by kishanjasani** [comment]
It doesn't look good with the logo. It will be better if we hide the site title and description when we select the logo. Here is the tested screenshot of this PR 

screenshot-twentyone local-2020 10 12-16_35_31

**Comment by aristath** [comment]
> It doesn't look good with the logo. It will be better if we hide the site title and description when we select the logo.

It'd be against automating or forcing this. It depends on the site, the logo and what the user wants to do. Some may want both depending on their logo. If someone wants to hide the title & description there's a checkbox to hide them on the same section where they upload the logo so they can already do that.

**Review by aristath — APPROVED** [review]
Code-wise this looks good to merge, as soon as it passes the design review we'll merge it :+1:

**Comment by melchoyce** [comment]
This should be fixed by #435 now, so closing. Thanks @JustinyAhin!

**Pull request closed without merging**
