### PR TITLE
Try adding blockquote styles

### PR DESCRIPTION
**Pull request by kjellr**
Alternate to #184. I spent a little time giving this a try too, and got it pretty close. 

Screen Shot 2020-10-15 at 4 04 10 PM

Should work well with left/center/right-aligned quotes. The only bug I know of at the moment is that the extra margin I add on small screen sizes to house the blockquotes is eaten up by higher-specificity global margins on the front end:

Screen Shot 2020-10-15 at 4 07 00 PM

I won't be able to work on solving that until tomorrow morning, so if someone else would like to pick this up feel free. If we get #184 cleaned up first, that's fine too. Thanks!

### CODE REVIEW

**Comment by ryelle** [comment]
I've iterated on this a bit to fix up the small screen quotes and some issues in the editor. The only question I have left is whether the de-bolding of `strong` should also affect the `cite` content — I've talked this through with @melchoyce and toggling bold on in the quote correctly unbolds the content, but if you bold something in the citation it does nothing right now.

Some screenshots from Mac/Firefox:

<details>
<summary>Front end, desktop</summary>

Screen Shot 2020-10-15 at 19 00 15-fullpage

</details>

<details>
<summary>Editor, desktop</summary>

Screen Shot 2020-10-15 at 19 02 01-fullpage

</details>

<details>
<summary>Front-end, mobile</summary>

Screen Shot 2020-10-15 at 19 11 51-fullpage

</details>

**Comment by ryelle** [comment]
@melchoyce mentioned the citations should not be italics, so I've pushed a fix for that; and I also noticed that things were out of alignment in the editor on a wide screen (wider than my screenshot above), so I've fixed that too.

**Review by melchoyce — APPROVED** [review]
LGTM 👍

**Comment by carolinan** [comment]
This is a comparison between this PR (right) and https://github.com/WordPress/twentytwentyone/pull/453

quote

And I think they both have _different_ issues, with the alignments, weight, and the citation.

**Comment by kjellr** [comment]
Thank you for the improvements, @ryelle!

> I think they both have different issues, with the alignments, weight, and the citation.

Regarding the alignments, this PR intentionally leaves off the quotation mark accent on the center version, and right-aligns it when the quote is right aligned. I prefer that to the treatment in #453. 

This PR uses a 600 font weight for the text instead of 700. The theme uses 600 for bold headings and the pagination titles and that's what I pulled that from, but I see that the pullquote block and widget font titles use a 700 weight. We may want to align those, but I'll leave it to @melchoyce to make the final call on that. 

It looks like #453 adds a hyphen + a non-breaking space before the citation (If we go with that, typography rulebooks typically suggest it should be an em-dash instead of a hypen). In general though, I personally prefer letting users enter that themselves.

**Comment by carolinan** [comment]
-Then let's use this one.

I can't take preference in consideration if it is not documented why decisions were made.

**Comment by melchoyce** [comment]
This PR more accurately reflects the design I intended.

> This PR uses a 600 font weight for the text instead of 700. The theme uses 600 for bold headings and the pagination titles and that's what I pulled that from, but I see that the pullquote block and widget font titles use a 700 weight. We may want to align those, but I'll leave it to @melchoyce to make the final call on that.

Let's go with 700 👍 

> It looks like #453 adds a hyphen + a non-breaking space before the citation (If we go with that, typography rulebooks typically suggest it should be an em-dash instead of a hypen). In general though, I personally prefer letting users enter that themselves.

Yeah, @ryelle asked me about this too, and I said I'd rather leave it up to people to add it if they want it.

**Comment by kjellr** [comment]
> Let's go with 700

Updated!

**Comment by carolinan** [comment]
The conflict needs to be resolved, but I am not sure what else this PR is waiting for?

**Review by aristath — APPROVED** [review]
Code looks good to me, and since design has already approved it I believe this is OK to merge :+1:

**Comment by aristath** [comment]
Resolved merge conflicts and merged

**Pull request merged**
