### PR TITLE
Update vertical margins for full width blocks

### PR DESCRIPTION
**Pull request by carolinan**
Related to https://github.com/WordPress/twentytwentyone/issues/536
And discussed on WordPress Slack https://wordpress.slack.com/archives/C02RP4VMP/p1604327710441600 (Account needed).

## Summary

1. Removes an editor style that removed the vertical margin from _all_ full width blocks.
1. Removes the vertical margin from the full width cover block and full width media & text block
in the editor and the front.

This way we can place two full width cover blocks or media & text blocks after each other without spacing, creating layouts that is not possible with spacing in between them.

(I also tested it with the columns block, but the result was not good.)

## Test instructions

This PR can be tested by following these steps:
1. Create a cover block and set it to full width. Duplicate the block.
1. Create a media and text block and set it to full width. Duplicate the block.
1. View the spacing in the editor.
1. Save and view the spacing on the front.
1. If you like, create a full width group block with a background color, duplicate it and compare. 
1. Imagine all the ways this can be combined to create layouts.

## Screenshots

vertical-front

## Quality assurance
* [x] I have thought about any security implications this code might add.
* [x] I have checked that this code doesn't impact performance (greatly).
* [x] I have tested this code to the best of my abilities
* [x] I have checked that this code does not affect the accessibility negatively

### CODE REVIEW

**Review by kjellr — APPROVED** [review]
This looks great in my testing. Would it make sense to also implement this for the ~Cover~ Group block in this PR? In my testing, that block has margins in the editor, but not in the front end so far: 

Editor|Front End
---|---
Screen Shot 2020-11-04 at 11 39 52 AM|Screen Shot 2020-11-04 at 11 39 42 AM

If you want to leave that to a separate PR that's fine too — this one is good to go as is.

**Comment by carolinan** [comment]
It was supposed to be fixed, not sure how I missed that 🙃

Ah, maybe I only tested a cover block with a background image.

**Comment by kjellr** [comment]
Oh whoops, sorry — I wrote "Cover" above, but I meant "Group" block. 😅 

The Cover block is working great! I was wondering if we want to add the Group block to this PR too. No worries if not, that can be handled separately.

**Comment by carolinan** [comment]
> Oh whoops, sorry — I wrote "Cover" above, but I meant "Group" block. 😅
> 
> The Cover block is working great! I was wondering if we want to add the Group block to this PR too. No worries if not, that can be handled separately.

Yes makes sense when the group has a background color.

**Pull request merged**
