### PR TITLE
Update starter content

### LINKED ISSUE #1: Add starter content
Starter content makes it easier for users to get started with editing their front page.
It populates menus, widget areas, and can set the front page to be static page. It is also possible to assign featured images.

The starter content front page should reflect the front page of the figma design.
We are able to use markup for blocks inside the content itself and this would be a good opportunity to showcase block patterns.
Images placed directly in the starter content will not be in the media library but in the theme folder.

Because any text content needs to be translated, the earlier we can decide the text, the better. 
The amount of text should be limited for the same reason.

**What kind of images do we want to use for the front page?**
Art? Photography? 
Neutral "block themed" images as in 2020?
-Are there any female artists in the community that we want to highlight?

### PR DESCRIPTION
**Pull request by carolinan**
Fixes #1

## Summary
Adds block patterns and text to the starter content.

## Relevant technical choices:
No
(The social links in the footer menu can not be tested until the menu has been merged.)

## Test instructions
Starter content can only be tested on fresh sites.

This PR can be tested by following these steps:
1. Reset your WordPress install or set up a new fresh install
2. Install and activate the theme
3. Go to the customizer and view the starter content.

## Quality assurance
* [x] I have thought about any security implications this code might add.
* [x] I have checked that this code doesn't impact performance (greatly).
* [x] I have tested this code to the best of my abilities
* [x] I have checked that this code does not affect the accessibility negatively

## Screenshot
start

### CODE REVIEW

**Comment by carolinan** [comment]
There probably needs to be a spacer block between the large text pattern and the overlapping images

**Comment by melchoyce** [comment]
Do you mind if I take a stab at polishing this in-editor? I can copy/paste the HTML output here after.

**Comment by carolinan** [comment]
I don't mind

**Comment by carolinan** [comment]
I think it also needs a third widget to fill that space on the right side.

**Comment by melchoyce** [comment]
Added a proposal to the issue: https://github.com/WordPress/twentytwentyone/issues/1#issuecomment-709484176

**Comment by kjellr** [comment]
Just pushed a few commits to include @melchoyce's latest content. 

Screenshot: 

ready-lemming jurassic ninja_

**Comment by carolinan** [comment]
There is too much text content: If nothing else, people will not have enough patience to read all 3 blocks. I would go as far as saying reduce it to one text block.

**Comment by pattonwebz** [comment]
The less text we include here the easier it is for the translators to tackle it.

**Comment by carolinan** [comment]
It showcases the borders and overlaps beautifully

**Comment by carolinan** [comment]
Maybe if there was a little more spacing or perhaps a dash of bold inside the text 3 columns so that the block of text breaks up a little.

**Comment by kjellr** [comment]
Here's a brief rewrite to shorten those sections. I'm not sure we can get shorter than this without either removing a column or removing explanations for how to use these features. Let me know what you think:

Screen Shot 2020-10-16 at 10 14 38 AM

**Comment by carolinan** [comment]
I like this :)

**Comment by melchoyce** [comment]
Works for me 👍

**Review by melchoyce — APPROVED** [review]

**Review by pattonwebz — APPROVED** [review]
Looks good to me, thanks for the content rewrite @kjellr. I agree we probably can't make it much shorter than this.

**Pull request merged**
