### PR TITLE
Change position absolute to fixed

### LINKED ISSUE #539: Mobile: The primary menu causes a horizontal scroll
**Describe the bug**
Testing trunk on Huawei P20 android 5.8inch 2244 × 1080 px.

When the primary menu is used, there is an horizontal scroll.
**When no menu is set on this location, the scroll is no longer present.**

**Screenshots**
Here I dragged the content to the left. I was not sure how else to get a screenshot of the horizontal movement.

Chrome:
thumbnail_Screenshot_android chrome

Firefox:
thumbnail_Screenshot_mozilla firefox

### PR DESCRIPTION
**Pull request by rolf-yoast**
Fixes https://github.com/WordPress/twentytwentyone/issues/539

## Test instructions

This PR can be tested by following these steps:
1. Check on mobile view without a logo if the site won't scroll horizontal if a primary menu is set.

## Quality assurance
* [x] I have thought about any security implications this code might add.
* [x] I have checked that this code doesn't impact performance (greatly).
* [x] I have tested this code to the best of my abilities
* [x] I have checked that this code does not affect the accessibility negatively

### CODE REVIEW

**Comment by carolinan** [comment]
With this PR, the content of the menu is being cut off.
The first menu item is not visible (only the description is visible)

menu

**Review by GuidoOffermans — APPROVED** [review]
CR 👍

**Comment by carolinan** [comment]
With all the changes to the menu, there was a reason why we could not change the `overflow`, but I do not see it documented in the conversation in the previous pull requests.

**Comment by carolinan** [comment]
I have tested https://github.com/WordPress/twentytwentyone/pull/582/commits/deeea29d9ea405947d8cba84dcf0614b8300878d
 with `overflow-x: scroll` and with ` overflow-x: hidden`;

Both variants resolves the issue with the horizontal scroll for me.

**Pull request merged**
