### PR TITLE
Post Formats

### LINKED ISSUE #367: Add Post Formats support
Now that we're in a good place with the base of the theme, let's consider adding some minimal post formats support.

Let's take a look at what the archive could look like:

Archive

[Figma mockup](https://www.figma.com/file/OEtsCj8oD8JPVx4OvsS0U2/Twenty-Twenty-One?node-id=363%3A0)

## Standard

Exactly as the archive exists now. Title, featured image if selected, excerpt.

## Image

If there's a featured image, use the featured image. If there isn't the featured image, pull out the first image block from the content and display it above the excerpt.

## Video

Pull out the first video or video embed block (VideoPress, YouTube, Vimeo, Dailymotion, TikTok) from the content and show it above the excerpt. 

## Aside and Status

Don't show the post title. Show the post content in larger text (Large Paragraph style) instead of an excerpt.

## Gallery

Pull out the first gallery in the post and show it above the excerpt.

## Audio

Pull out the first audio block or audio embed block (SoundCloud, Spotify, Mixcloud) from the content and show it above the excerpt.

## Link

If possible, show the first link as the excerpt in larger text (Large Paragraph style). If not, show the first paragraph of the content in larger text, retaining formatting.

## Quote

Pull out the first quote or pullquote block from the content and display it instead of the excerpt.

## Chat

Show the first two paragraphs of the content, retaining formatting.

### PR DESCRIPTION
**Pull request by aristath**
Fixes #367 

## Summary

Currently WIP - do not merge. In this 1st pass I'll only do block-based content since this is the most urgent part. Once that is done we can move on to legacy content.

## Tasks
* [x] `image`: If there's a featured image, use the featured image. If there isn't the featured image, pull out the first image block from the content and display it above the excerpt.
* [x] `video`: Pull out the first video or video embed block (VideoPress, YouTube, Vimeo, Dailymotion, TikTok) from the content and show it above the excerpt.
* [x] `aside`: Don't show the post title. Show the post content in larger text (Large Paragraph style) instead of an excerpt.
* [x] `status`: Don't show the post title. Show the post content in larger text (Large Paragraph style) instead of an excerpt.
* [x] `gallery`: Pull out the first gallery in the post and show it above the excerpt.
* [x] `audio`: Pull out the first audio block or audio embed block (SoundCloud, Spotify, Mixcloud) from the content and show it above the excerpt.
* [x] `link`: If possible, show the first link as the excerpt in larger text (Large Paragraph style). If not, show the first paragraph of the content in larger text, retaining formatting.
* [x] `quote`: Pull out the first quote or pullquote block from the content and display it instead of the excerpt.
* [x] `chat`: Show the first two paragraphs of the content, retaining formatting.

## Test instructions

This PR can be tested by following these steps:
1. 
2. 
3. 

## Quality assurance
* [x] I have thought about any security implications this code might add.
* [x] I have checked that this code doesn't impact performance (greatly).
* [x] I have tested this code to the best of my abilities
* [x] I have checked that this code does not affect the accessibility negatively

### CODE REVIEW

**Comment by aristath** [comment]
~~Note to self: audio &video (basically all embed blocks) don't work in archives, I'll need to investigate and fix.~~
EDIT: fixed in https://github.com/WordPress/twentytwentyone/pull/391/commits/082ea5412835890535aa53e50e8c4abb909d38c0 by applying `the_content` filters.

**Comment by aristath** [comment]
post-formats have a specific purpose and this implementation made some reasonable assumptions. For example an audio post-format is expected to include an audio or embed block. If it doesn't contain an audio block, then it's likely content created using the legacy editor and not the block editor, or uses a custom block for the audio, or has custom content that should be printed verbatim in order for the audio to embed. With that in mind, if it doesn't find an audio or embed block it will fallback to the full content so that the audio gets rendered properly. The same logic applies to videos and other post-formats.

## Aside

Prints the full content.

## Audio

Tries to print the first `core/embed` block.
If there is no `core/embed` block in the content, tries to print the 1st `core/audio` block.
If a `core/embed` or `core/audio` block were found, it adds the excerpt. If no viable blocks were found, it prints the full content (most likely will be an audio with not a lot of extra content).

## Chat

Prints the first 2 `core/paragraph` blocks.
If there are no paragraph blocks, prints the excerpt.

## Gallery

Prints the 1st `core/gallery` block. If a block is found, it appends the excerpt. If no block is found, then it prints the full content.

## Image

Prints the featured image.
If no featured image exists, it prints the 1st `core/image` block.
If a featured image or image block were found, it appends the excerpt. If not, it prints the full content.

## Link

Prints the 1st `core/paragraph` block.
If no paragraph block exists, it prints the full content.

## Quote

Prints the 1st `core/quote` block.
If there is no `core/quote` block, prints the 1st `core/pullquote` block.
If there were no quote or blockquote blocks, prints the full content.

## Status

Prints the full content.

## Video

Prints the 1st `core/embed` block.
If no video block exists, print the 1st `core/video` block.
If a block was found append the excerpt, otherwise print the full content.

**Comment by carolinan** [comment]
Should the post title be hidden for the aside in the archives?

**Comment by aristath** [comment]
Just my 2c, I think we should merge this one ASAP so that more people can test post-formats and we have time to fix any issues that arise.

**Comment by carolinan** [comment]
OK, merging to enable more testing.

**Pull request merged**
