### PR TITLE
Dark Mode: Show toggle button in the editor

### PR DESCRIPTION
**Pull request by ryelle**
## Summary
There's code to inject the Dark Mode toggle into the editor, but it's not currently showing up (or working correctly). This PR should fix the display, z-indexing, and JS to let authors cycle the dark mode on and off while writing.

## Relevant technical choices:
The toggle code in `dark-mode-toggler.js` now checks for `twentytwentyoneDarkModeEditorToggleEditorStyles` & runs that, to make sure we toggle the `is-dark-mode` class from `.editor__typewriter`. It's not the most straightforward method, but it lets us avoid adding a lot of wp-admin code into `dark-mode-toggler.js` or duplicating code into separate toggle functions.

## Test instructions

This PR can be tested by following these steps:
1. Edit a post/page
2. See the Dark Mode button in the bottom right corner
3. It should not be obstructed by any other element
4. Clicking it should toggle dark mode
5. Clicking it again should toggle dark mode again

Check that the frontend toggle still works too.

## Screenshots

Before, note no visible dark mode button:

before-no-sidebar
before-sidebar

After, button is visible with sidebar open or closed:

after-light-sidebar
after-dark-sidebar
after-light-no-sidebar

## Quality assurance
* [x] I have thought about any security implications this code might add.
* [x] I have checked that this code doesn't impact performance (greatly).
* [x] I have tested this code to the best of my abilities
* [x] I have checked that this code does not affect the accessibility negatively

### CODE REVIEW

**Comment by carolinan** [comment]
But this button was hidden on purpose, I do not agree that adding it back is the best sollution.

The button is a completely new UI element that is unique for this theme that people would need to learn. 
No other buttons are placed in the editor content this way. It is not an UI that would ever be extended: Nor used by WordPress core if we want to continue working on making Dark Mode available in core. 
It is confusing and an accessibility issue to add yet another functionality inside the content of the editor. 
It distracts from the editing.

**Comment by ryelle** [comment]
> But this button was hidden on purpose, I do not agree that adding it back is the best sollution.

Ah, okay — I saw that it still technically existed on the page, and was just hidden with a `display: none` which seemed to be added in this print style PR https://github.com/WordPress/twentytwentyone/pull/788, so I assumed it was a bug.

If this is meant to be removed, the code should not be injected into the editor at all. I'll close this PR & open another to do that 👍

**Comment by ryelle** [comment]
Is there a place where that decision was made (to remove the button in the editor) that I can link to in that new PR?

**Comment by carolinan** [comment]
> Is there a place where that decision was made (to remove the button in the editor) that I can link to in that new PR?

It _should_ have been documented in an issue for the PR that hid the button. I'll update when I locate it.

**Pull request closed without merging**
