### PR TITLE
Add a z-index value to the overlapping columns block style

### PR DESCRIPTION
**Pull request by kjellr**
This adds a `z-index` value to the overlapping columns block style, in order to ensure that the foremost column appears in front of blocks that have a z-index value assigned (like the Cover block). 

Before: 

Screen Shot 2020-10-12 at 9 54 26 AM

After:

Screen Shot 2020-10-12 at 9 54 16 AM

### CODE REVIEW

**Comment by kjellr** [comment]
@melchoyce In addition to the cover block, wasn't there another core block that we saw this issue with? I can't remember which one, but I want to make sure the z-index value here overrides that one too.

**Review by aristath — APPROVED** [review]
After running `npm run build` this looks good :+1:

**Comment by melchoyce** [comment]
The other overlapping block was Gallery, but this PR fixes it 👍 

Before | After
----- | -----
image | image

**Review by melchoyce — APPROVED** [review]
LGTM 👍

**Pull request merged**
