### PR TITLE
Change text color to white in IE if using a dark background

### PR DESCRIPTION
**Pull request by aristath**
## Summary
In IE11, when using a dark background-color the text doesn't switch to white and is unreadable.
This PR detects if the user is on IE and if they are using a dark background-color then it switches the text-color to white.

## Quality assurance
* [x] I have thought about any security implications this code might add.
* [x] I have checked that this code doesn't impact performance (greatly).
* [x] I have tested this code to the best of my abilities
* [x] I have checked that this code does not affect the accessibility negatively

### CODE REVIEW

**Comment by carolinan** [comment]
This is so much better, but there are still elements where the specificity overrides the colors.
<del>I think this specificity can be removed but it needs to be tested.</del>
_Or it can't be removed of course, because it allows us to use the variables to change these._

Example:
.entry-title , .site-title when not linked

All the text and links in the footer:
`.footer-navigation-wrapper li a:link`
`.site-footer > .site-info a:visited`

**Comment by aristath** [comment]
Added more selectors, I don't see anything else missing now 👍

**Comment by carolinan** [comment]
The responsive menu has the mint green background color when it is opened, do we open a separate issue for this?
responsive-ie

**Comment by carolinan** [comment]
Skip link is not readable when focused:

ie-skiplink

**Comment by carolinan** [comment]
The button block, submit and search buttons work well on the default background color.
When the background color is dark, the text is invisible when you hover over/activate the button.

The dark color I had selected from the palette, is the dark color that is also the default text color 🤦

**Comment by aristath** [comment]
> The responsive menu has the mint green background color when it is opened, do we open a separate issue for this?

Fixed

**Pull request merged**
