### PR TITLE
Try fixing the border for search fields with inset buttons

### PR DESCRIPTION
**Pull request by kjellr**
Before: 

Screen Shot 2020-12-01 at 11 47 48 AM

After:

Screen Shot 2020-12-01 at 11 47 38 AM

### CODE REVIEW

**Comment by allancole** [comment]
Looks good! Only thing is the hover state looks like it doesn’t have enough contrast. 




Maybe on hover, the background-color can be that dark grey?

**Comment by luminuu** [comment]
This PR looks good to me, I do not have these hover issues @allancole posted. WP 5.6 RC1-49715 without Gutenberg plugin.

**Comment by carolinan** [comment]
I don't see the hover issue either

**Comment by allancole** [comment]
Ahhh, I needed to turn off the Gutenberg plugin! Looks good to me now too :-)

**Pull request merged**
