### PR TITLE
Add wp-env with some supporting docs.

### PR DESCRIPTION
**Pull request by whyisjake**
To aid local development, I added some docs on how to use `wp-env` for local testing.

[Full docs are here](https://developer.wordpress.org/block-editor/packages/packages-env/).

### CODE REVIEW

**Comment by carolinan** [comment]
Hi, there is already a pull request for this, can you work together with @fabiankaegy on it?

Both PR's include scripts for linting. css files. This was removed earlier because it was pointed out that if the scss lint passes, so does the css.

It is unclear to me, why was the order of the scripts changed?

**Comment by fabiankaegy** [comment]
Hi @whyisjake, The PR I've been working on is #123 with the issue #124 to track the conversations about it. Would love your insights / thoughts especially on the docs side of things.

**Comment by jffng** [comment]
> why was the order of the scripts changed?

Perhaps best practice to keep the scripts in alphabetical order, since @whyisjake added a few related to `wp-env`.

**Comment by carolinan** [comment]
Sorry about the confusion about the script for linting CSS files. It hasn't been merged yet but was fresh in my memory.

**Comment by luminuu** [comment]
Already done in #124.

**Pull request closed without merging**
