### PR TITLE
Composer improvements

### LINKED ISSUE #9: Code quality: Add Github actions for pull requests
Each pull request should be checked for PHP compatibility and to ensure that coding standards are followed.

### PR DESCRIPTION
**Pull request by dingo-d**
I've made some updates to `composer.json` (structure, packages, scripts). I've added a basic `phpstan` config and added a new GH action.

This will override #60 and fix #9

### CODE REVIEW

**Comment by dingo-d** [comment]
@aristath Should I remove the extra phpcs lint action that was merged? Since this is covered by one of the steps in the code quality checks one.

**Comment by aristath** [comment]
Definitely :+1: 
The one we currently have will need to be removed when this gets merged.
I think the only blocker for this one is https://github.com/WPTT/WPThemeReview/pull/257

**Comment by dingo-d** [comment]
Yeah, we'll have the block on phpcs until WPThemeReview is resolved and merged

**Comment by dingo-d** [comment]
Alternatively, we can just silence this error in the `phpcs.xml.dist` 🤷‍♂️

**Comment by aristath** [comment]
> Alternatively, we can just silence this error in the `phpcs.xml.dist` 🤷‍♂️ 

I suppose that would be an acceptable solution so we can get this merged... We know we're using it right and the errors reported are false-positives so we can do that, and once the fix lands in the WPThemeReview CS we can remove the exception :+1:

**Comment by dingo-d** [comment]
I mean, you can merge it and then do a PR with phpcs exclusion and fixes for PHPStan issues? That way we keep these two separate, as this PR is just for adding actions and configuration fixes.

**Pull request merged**
