### PR TITLE
Add a screen reader text with the site title to the front page

### LINKED ISSUE #251: Site title and tagline are removed completely when display option unchecked
When the option to display the site title and tagline is unchecked in the Customizer, the site branding is removed completely. The template part is [not included](https://github.com/WordPress/twentytwentyone/blob/691ae72442f425beceec347088ea4c2c3d6f5474/template-parts/header/site-branding.php#L10) anymore, even when there is no custom logo added.

Shouldn't we rather make them visually hidden for accessibility (and search engines), similar to how we do it for screen reader texts?

### PR DESCRIPTION
**Pull request by carolinan**
Fixes https://github.com/WordPress/twentytwentyone/issues/251

### CODE REVIEW

**Comment by carolinan** [comment]
@LittleBigThing Is this how you intended it? It does not add the site title to pages that already has an H1.

It also does not solve the missing H1 if the title field is empty, but that is very much an edge case.

**Comment by ryelle** [comment]
This works for "latest posts" as home, but not for pages — it's now showing two headings on the homepage & none on the posts page.

**Comment by carolinan** [comment]
Should we just move the page titles down one heading level and always use the site title as the H1?

**Review by aristath — APPROVED** [review]
LGTM :+1:

**Pull request merged**
