### PR TITLE
Quote & Pullquote block: Update symbol position

### LINKED ISSUE #835: Pullquote: when we select the solid color style then the " (Quote) gets overlap with placeholder #26885
This issue originally was created by @kmadhak over on the the Gutenberg repo (https://github.com/WordPress/gutenberg/issues/26885).

----

Describe the bug
in Pullquote when we select the solid color style then the " (Quote) get overlap with placeholder, so because of that we are not able to view the first character of the text of Pullquote.

To reproduce
Steps to reproduce the behaviour:

Go to 'Editor'
1. Add new page
2. Click on 'add block'
3. Select the block 'Pullquote'
4. Select the Style 'Solid color'
5. View the placeholder 
6. See error

Expected behaviour
when we select the solid colour style the we have to view the full placeholder and text of Pullquote.

Screenshots
https://prnt.sc/tvn4la
https://prnt.sc/tvn53e

Video
for more detail please view the attached video
https://www.loom.com/share/051a4b5a408049979bc99274924a5fba

Editor version:
WordPress version: 5.6-beta3-49560

Desktop:
OS: Windows
Browser chrome
Version 86.0.4240.193 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by carolinan**
Partial fix for https://github.com/WordPress/twentytwentyone/issues/549
Fixes https://github.com/WordPress/twentytwentyone/issues/835

## Summary

When the quote block has right aligned text:
Hides the original, left aligned quote symbol.
Places a new quote symbol left of the text itself.
Resets the absolute position for the pullquote block so that the symbol is above the text.

https://github.com/WordPress/twentytwentyone/pull/832/commits/c1bf9a9df209b2bc674755d203ba70f45e37bb45 Fixes the position of the symbol on the front when the text has the default alignment.

Also: Removes the left border that is visible on the default quote on the front.

## Test instructions

This PR can be tested by following these steps:
1. Add two quotes blocks.
1. Align one of quotes to the right.
1. Confirm that the default block and the right aligned block matches, except the text is right aligned.

## Screenshots
Editor:
Before
quote-editor

After
quote-editor-after

---
Front:
Before
quote-front

After:
quote-front-after

----

It does not fix the position of the symbol for "classic" quotes:
classic-quote-front

## Quality assurance
* [x] I have thought about any security implications this code might add.
* [x] I have checked that this code doesn't impact performance (greatly).
* [x] I have tested this code to the best of my abilities
* [x] I have checked that this code does not affect the accessibility negatively

### CODE REVIEW

**Comment by aristath** [comment]
In a previous PR it was mentioned that the symbol should not have position:absolute but instead be on the previous line: https://github.com/WordPress/twentytwentyone/pull/787#issuecomment-721802618
Did we decide to place it with postition:absolute instead? :thinking:

**Comment by carolinan** [comment]
I can't keep up with these changes.

So the pull quote and quote should have the same style. 

Does anyone have time to redo this?

**Comment by carolinan** [comment]
Can figma be updated to match the final design? 

The editor and front needs to match, no matter wich style  that is selected 🙂

**Comment by melchoyce** [comment]
What I'm seeing in the editor looks visually correct for the Quote block:

image

Only the Pullquote block styles should use quotation marks above the quote:

**Comment by carolinan** [comment]
> What I'm seeing in the editor looks visually correct for the Quote block:

Is this image with the pr applied? 
Because the symbol for the right aligned text is in the wrong position in this image.

**Comment by melchoyce** [comment]
No, this is without the PR.

**Comment by carolinan** [comment]
I suspect that if we change the position of the symbol for the classic/legacy quote, it will also affect the pull quote. I will test shortly.

**Comment by carolinan** [comment]
Editor: This is copy pasted so ignore the spacing between the blocks.

editor

**Comment by carolinan** [comment]
Front

I did not include both the left aligned and right aligned **solid** pull quote in the screenshot, as you can see it is broken, but, this is not related to this pull request:

'front

**Review by ryelle — APPROVED** [review]
Looks good, removes the border & fixes the quote alignment. The linter error in the checks is a false failure, this PR was created before the fix in #847

**Pull request merged**
