### PR TITLE
fix: Gallery item's link showing bottom border in Classic Editor case for Post Format Gallery

### LINKED ISSUE #157: Post Format - Gallary: Remove border-bottom for all images in gallary item
**Describe the bug**
All gallery images have border-bottom. It's not supposed to have a border-bottom on each element of the gallery image.

**To Reproduce**
1. Take the post format: Gallary
2. Add gallery in the classic editor
3. You will get underlined in each image.

**Expected behavior**
There should not be a border-bottom.

**Screenshots**
gallery_issue

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.5.1]

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - Browser [e.g. chrome]

### PR DESCRIPTION
**Pull request by imnavanath**
Issue Fix: #157 
- Added initial border style `transparent` for Gallery item.

### CODE REVIEW

**Comment by kishanjasani** [comment]
@imnavanath Can we use border-bottom to `none` instead of `transparent`?

**Comment by carolinan** [comment]
Hi
For the theme be accessible, the user needs to be able to tell that the image is linked. A visible indicator needs to be present when the link is focused and hovered.

Because all links are being restyled, it would be better to wait with styling the galleries until there is a final decision for how the links should look,  if we are moving forward with using an underline or using a border.
See https://github.com/WordPress/twentytwentyone/issues/110 and https://github.com/WordPress/twentytwentyone/pull/133

**Comment by carolinan** [comment]
And there is also no intention to support the classic editor.

**Comment by carolinan** [comment]
@imnavanath Hi again, I believe that the problem has been solved with another pull request that updated the link styles. 
I no longer see a visible underline below the classic gallery items.
I will close this pull request.

Please reply with your WordPress.org user name so that I can add you do the contributors list -or, make a new pull request and add your user names to https://github.com/WordPress/twentytwentyone/blob/trunk/CONTRIBUTORS.md

**Comment by imnavanath** [comment]
Thanks @carolinan, got your point :+1: 
BTW, here are my usernames - 
`Github username - imnavanath
WordPress username - navanathbhosale
`

**Comment by imnavanath** [comment]
@carolinan can you please review & merge [the PR](https://github.com/WordPress/twentytwentyone/pull/586). 
Thank you.

**Pull request closed without merging**
