### PR TITLE
Increase clickable area for list links.

### PR DESCRIPTION
**Pull request by aristath**
## Summary
Fixes an a11y issue reported by lighthouse, where the clickable area for links inside lists in widget areas is not large enough.
Visually there is no real difference, but it's easier to target and click the links.

## Quality assurance
* [x] I have thought about any security implications this code might add.
* [x] I have checked that this code doesn't impact performance (greatly).
* [x] I have tested this code to the best of my abilities
* [x] I have checked that this code does not affect the accessibility negatively

### CODE REVIEW

**Review by carolinan — CHANGES_REQUESTED** [review]
The added padding is being overwritten by WordPress recent comment style
`recent_comments_style`

https://developer.wordpress.org/reference/classes/wp_widget_recent_comments/recent_comments_style/


For other listed links in widgets, the clickable area is larger, but not 44px44px.

**Comment by aristath** [comment]
> The added padding is being overwritten by WordPress recent comment style

Fixed (added filter)

> For other listed links in widgets, the clickable area is larger, but not 44px44px.

I don't think that rule applies to text... :thinking:

**Comment by carolinan** [comment]
> I don't think that rule applies to text... 🤔

Then what did lighthouse complain about 🤔 -I'll test again.

**Comment by carolinan** [comment]
Before:
before


After:
after

**Comment by enriquesanchez** [comment]
@aristath I wasn't able to reproduce this with Lighthouse, would you have more info on the reported issue? 

I honestly find the list harder to read with the increased padding, it breaks the reading flow between items.

**Comment by aristath** [comment]
I completely forgot about this PR... Yes,you are right,  it does indeed make it harder to read. I'm closing this since it looks like we'll increase the font-size instead (https://github.com/WordPress/twentytwentyone/issues/578)

**Pull request closed without merging**
