### PR TITLE
Hide author bio when no description

### LINKED ISSUE #232: Option to hide the author’s biography
With Twenty Twenty One, the author's biography with its avatar always appears on single posts. Some users might want to hide it.
Twenty Twenty has an option inside the Customizer to hide the biography while Seedlet & Twenty Twenty Nineteen only displays it if the user has entered a description:
`if ( (bool) get_the_author_meta( 'description' ) ) :`

### PR DESCRIPTION
**Pull request by ct-martin**
Fixes #232 

Shameless copy-paste :sweat_smile:

image

### CODE REVIEW

**Comment by carolinan** [comment]
This works, but the post has no other author name, I don't think that is ideal for example when there is more than one author.

**Comment by melchoyce** [comment]
[Added two ideas to the issue](https://github.com/WordPress/twentytwentyone/issues/232#issuecomment-703844839).

**Comment by carolinan** [comment]
👋 @ct-martin  what is your WordPress.org username, for the contributors list?

**Comment by ct-martin** [comment]
👋 it's CTMartin0; do you want me to make a PR to add it?

On Oct 6, 2020 11:39 PM, Carolina Nymark <notifications@github.com> wrote:

👋 @ct-martin<https://github.com/ct-martin> what is your WordPress.org username, for the contributors list?

**Comment by melchoyce** [comment]
Hey @ct-martin! What's your WordPress.org username?

**Pull request merged**
