### PR TITLE
Fix blockquote:before position

### LINKED ISSUE #759: Pullquote: Quotation mark positioning regression
**Describe the bug**
The text overlaps the quotation mark in the Pullquote block now:

image

**To Reproduce**
1. Make a new post or page.
2. Add a pullquote block.
3. See that the quotation mark overlaps the text now.

**Expected behavior**
It should look like this:

image
https://2021.wordpress.net/2020/10/16/a-love-of-nature/

**Editor version (please complete the following information):**
- WordPress version: 5.6-beta2-49360
- Gutenberg: 9.2.2

### PR DESCRIPTION
**Pull request by aristath**
Fixes #759 

This is an alternative to #766. Takes a different approach, simply changing the left position.
Tested with the blockquotes from the [Theme Unit Test Data XML](https://raw.githubusercontent.com/WPTRT/theme-unit-test/master/themeunittestdata.wordpress.xml)

## Quality assurance
* [x] I have thought about any security implications this code might add.
* [x] I have checked that this code doesn't impact performance (greatly).
* [x] I have tested this code to the best of my abilities
* [x] I have checked that this code does not affect the accessibility negatively

### CODE REVIEW

**Comment by kjellr** [comment]
With this PR, I'm still seeing the editor appear incorrectly: 

Screen Shot 2020-11-04 at 10 30 21 AM

And also, based on @melchoyce's comp [in the original issue](https://github.com/WordPress/twentytwentyone/issues/759) and [the example in Figma](https://www.figma.com/file/OEtsCj8oD8JPVx4OvsS0U2/Twenty-Twenty-One?node-id=1046%3A0), I believe the quotation mark should appear on its own new line in the pullquote block. 

97736989-ccf45e80-1ab2-11eb-8881-777259794bb4

**Comment by aristath** [comment]
In that case we don't even need the position:absolute... Removed it and I now get this as expected:

Screenshot_2020-11-05 Block Quote – My Blog(1)

**Review by kjellr — APPROVED** [review]
🌟 Great!

**Comment by felipeelia** [comment]
Hi @aristath !

Don't you want to use the i18n change I suggested in #766 ? Thanks!

**Pull request merged**
