### PR TITLE
Try: New button styles

### PR DESCRIPTION
**Pull request by carolinan**
This is an experiment, do not merge until this has been discussed and carefully tested.
**The styles in this PR does not match the original design.**

## Summary

Resets the button styles to be closer to the block editor defaults.

New **focus style** that is the same for filled and outlined buttons:
1.  **No color changes** -respects the users custom colors
1. 2 pixel outline offset. 
1. 2 pixel **dotted** outline with the color `var(--button--color-background);`
This focus styles matches form input elements like the text area.

New **hover style** that is the same for filled and outlined buttons:
1.  **No color changes** -respects the users custom colors
1. 2 pixel outline offset. 
1. 2 pixel **solid** outline with the color `var(--button--color-background);`
This is outline is solid so that that the hover and focus styles are different.

**Focus:** 
Adds a :not style for buttons so that the background color for the button link is not white on focus.

**Outlined buttons:**
Overrides the editor default text color and uses `var(--button--color-background);` as the new text color.

**Filled buttons:**
Set the border to transparent. For a filled button with a border, use the outline button style with a background color instead. It's what the outline is for...

## Test instructions

This PR can be tested by following these steps:
1.
1.
1.

## Screenshots

Sample hover style: (the filled button with border, the outlined button with two borders)
hover

Sample focus style, dotted border:
focus

## Quality assurance
* [x] I have thought about any security implications this code might add.
* [x] I have checked that this code doesn't impact performance (greatly).
* [x] I have tested this code to the best of my abilities
* [x] I have checked that this code does not affect the accessibility negatively

### CODE REVIEW

**Comment by carolinan** [comment]
In https://github.com/WordPress/twentytwentyone/pull/872/commits/7b00410b163a3830d81a7a32ca7a44cea885a77a:

Because the border for the default button style was set to transparent, we need to add the border color to the search block.
Adjust the outline offset so that the outline is inside the button not outside.
-If the outline was left outside, it would not match the input field.

**Screenshots:**

Search button outside, focus:
button-outside-focus

Icon button inside, focus:
button-inside-focus

**Comment by carolinan** [comment]
In https://github.com/WordPress/twentytwentyone/pull/872/commits/b204d6aa9e234eb030e98197859aa7526c6cede8:

Because the border for the default button style was set to transparent, we need to add the border color to the submit button in the search widget.
Adjust the outline offset so that the outline is inside the button not outside.
-If the outline was left outside, it would not match the input field.

search-widget-submit-button-focus

**Comment by carolinan** [comment]
In https://github.com/WordPress/twentytwentyone/pull/872/commits/7be81bc31ceae6abe93e56693446fd294ff39305:

Add the :not style to the sass\style-dark-mode.scss file so that the button links to do not have a white background when focused.

**Comment by carolinan** [comment]
Test content, for when the buttons are not inside a block that has a background color:
```

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link" href="https://wordpress.org">default</a></div>
<!-- /wp:button -->

<!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link" href="https://wordpress.org">filled</a></div>
<!-- /wp:button -->

<!-- wp:button {"style":{"color":{"background":"#7200a3"}}} -->
<div class="wp-block-button"><a class="wp-block-button__link has-background" href="https://wordpress.org" style="background-color:#7200a3">filled with custom background</a></div>
<!-- /wp:button -->

<!-- wp:button {"style":{"color":{"background":"#a3006f","text":"#78cef3"}}} -->
<div class="wp-block-button"><a class="wp-block-button__link has-text-color has-background" href="https://wordpress.org" style="background-color:#a3006f;color:#78cef3">filled with custom background and custom text color</a></div>
<!-- /wp:button -->

<!-- wp:button {"style":{"color":{"background":"#a3006f"}},"textColor":"yellow"} -->
<div class="wp-block-button"><a class="wp-block-button__link has-yellow-color has-text-color has-background" href="https://wordpress.org" style="background-color:#a3006f">filled with custom background and palette text color</a></div>
<!-- /wp:button -->

<!-- wp:button {"backgroundColor":"red"} -->
<div class="wp-block-button"><a class="wp-block-button__link has-red-background-color has-background" href="https://wordpress.org">filled with palette background</a></div>
<!-- /wp:button -->

<!-- wp:button {"style":{"color":{"text":"#11b8ff"}},"backgroundColor":"red"} -->
<div class="wp-block-button"><a class="wp-block-button__link has-red-background-color has-text-color has-background" href="https://wordpress.org" style="color:#11b8ff">filled with palette background, and custom text color</a></div>
<!-- /wp:button -->

<!-- wp:button {"backgroundColor":"red","textColor":"white"} -->
<div class="wp-block-button"><a class="wp-block-button__link has-white-color has-red-background-color has-text-color has-background" href="https://wordpress.org">filled with palette background, and palette text color</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"className":"is-style-outline"} -->
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link" href="https://wordpress.org">outline</a></div>
<!-- /wp:button -->

<!-- wp:button {"style":{"color":{"text":"#4dc5f8"}},"className":"is-style-outline"} -->
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link has-text-color" href="https://wordpress.org" style="color:#4dc5f8">outline without background, with custom text color</a></div>
<!-- /wp:button -->

<!-- wp:button {"textColor":"purple","className":"is-style-outline"} -->
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link has-purple-color has-text-color" href="https://wordpress.org">outline without background, with palette text color</a></div>
<!-- /wp:button -->

<!-- wp:button {"style":{"color":{"background":"#7200a3"}},"className":"is-style-outline"} -->
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link has-background" href="https://wordpress.org" style="background-color:#7200a3">outline with custom background</a></div>
<!-- /wp:button -->

<!-- wp:button {"style":{"color":{"background":"#a3006f","text":"#78cef3"}},"className":"is-style-outline"} -->
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link has-text-color has-background" href="https://wordpress.org" style="background-color:#a3006f;color:#78cef3">outline with custom background and custom text color</a></div>
<!-- /wp:button -->

<!-- wp:button {"style":{"color":{"background":"#a3006f"}},"textColor":"yellow","className":"is-style-outline"} -->
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link has-yellow-color has-text-color has-background" href="https://wordpress.org" style="background-color:#a3006f">outline with custom background and palette text color</a></div>
<!-- /wp:button -->

<!-- wp:button {"backgroundColor":"red","className":"is-style-outline"} -->
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link has-red-background-color has-background" href="https://wordpress.org">outline with palette background</a></div>
<!-- /wp:button -->

<!-- wp:button {"style":{"color":{"text":"#11b8ff"}},"backgroundColor":"red","className":"is-style-outline"} -->
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link has-red-background-color has-text-color has-background" href="https://wordpress.org" style="color:#11b8ff">outline with palette background, and custom text color</a></div>
<!-- /wp:button -->

<!-- wp:button {"backgroundColor":"red","textColor":"white","className":"is-style-outline"} -->
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link has-white-color has-red-background-color has-text-color has-background" href="https://wordpress.org">outline with palette background, and palette text color</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons -->

<!-- wp:search {"label":"Search, default","buttonText":"Search"} /-->

<!-- wp:search {"label":"Search, button inside","buttonText":"Search","buttonPosition":"button-inside"} /-->

<!-- wp:search {"label":"Search, icon button outside","buttonText":"Search","buttonUseIcon":true} /-->

<!-- wp:search {"label":"Search, icon button inside","buttonText":"Search","buttonPosition":"button-inside","buttonUseIcon":true} /-->
```

**Comment by carolinan** [comment]
**On default and light body background color:**

When buttons are placed inside a group with the **grey** palette background color, the outlined button that has no custom colors is invisible since the button uses this color by default.

An exception can be added for this color.

grey-palette

**Comment by carolinan** [comment]
**With Dark Mode enabled**, buttons placed inside group blocks that has a light or white background color, uses the light grey color: `#f0f0f0;`, so they are visible, but barely.

white-palette

**Without dark mode but with a dark background color,** the button color is white, so it is invisible when the group block has a white background:

white-palette-regular-dark-background

**Comment by kjellr** [comment]
This is a complicated one. So many use cases to test against! 😅

I gave this a test myself, and it mostly works — the hover states didn't work in the front-end for me though. Aside from that, the only other issues I saw were the same ones you mentioned above. 

From design perspective however, I definitely prefer the existing button hover style — that style is a lot more bold and noticeable. Considering this one has problems of its own still, I'm not totally sure it makes sense to swap to this button design at this stage. Are #858 and #866 the only known issues with the current implementation? I know it's been a complicated thing to solve, but I wonder if it's possible to around those. I'll try to spend some time on it tomorrow too.

**Comment by carolinan** [comment]
The problem is keeping the custom colors _and_ "reverting" the solid button so that the text color becomes the background color vice versa, and make those colors visible over at least the palette background colors for default and Dark Mode

**Comment by carolinan** [comment]
Try placing any current button over a cover image, on hover or focus, it is not readable and this is a common use case.

**Pull request closed without merging**
