### PR TITLE
Add license info for the poplars image

### PR DESCRIPTION
**Pull request by kjellr**
Looks like this was left out of #150 by mistake.

### CODE REVIEW

**Review by melchoyce — APPROVED** [review]
LGTM 👍

**Comment by pattonwebz** [comment]
@melchoyce @carolinan are you working with any kind of merge policy here or anything. This one is approved and I feel could get merged right now but it hasn't been yet so I was curious if you were following any specific method or timeframes for that.

**Comment by melchoyce** [comment]
From my end, I'm mostly letting folks with merge capabilities merge their own work, and merging small things myself if I'm confident in the code (or not code, in this case). Anything really technical I'm leaving for devs to merge. I'll go ahead and merge this now.

**Comment by pattonwebz** [comment]
@melchoyce sounds like a good policy to have, I was just curious so thanks for the quick answer :)

**Pull request merged**
